### ISSUE TITLE
no types for express-validation

### ISSUE THREAD

**Issue by siluri** [AndrewKeig/express-validation#75] opened 2018-01-21 21:20 UTC
no types defined for import 
```javascript
import expressValidation from 'express-validation'
```

```bash
yarn add --dev @types/express-validation
```

**Comment by colthreepv** [comment] 2018-02-10 13:27
I approve of this issue, this library has not received an update in a while, but it's codebase it's so thin that it should be useful even nodaways.

**But nowadays standard is having typings!**  
I will apply a pr to typescript if I find the time

**Comment by colthreepv** [comment] 2018-02-10 17:25
closing as duplicate of #54

**Closed by colthreepv** 2018-02-10 17:25 UTC
Labels: enhancement, planned
